version: "2.1"
services:
    web:
        build: .
        image: pos/vendas
        container_name: vendas
        ports:
          - "8081:8080"
        depends_on:
            postgres:
                condition: service_healthy
        links:
            - "postgres:host-banco"
    postgres:
        build: ./postgres
        image: pos/postgres
        container_name: postgres
        ports:
            - "5433:5432"
        healthcheck:
            test: "exit 0"
